import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const contracts = [
  [
    "workChainTokenAbi",
    "artifacts/contracts/WorkChainToken.sol/WorkChainToken.json",
  ],
  [
    "workCertificateAbi",
    "artifacts/contracts/WorkCertificateNFT.sol/WorkCertificateNFT.json",
  ],
  [
    "workChainEscrowAbi",
    "artifacts/contracts/WorkChainEscrow.sol/WorkChainEscrow.json",
  ],
];

const exports = [];

for (const [name, artifactPath] of contracts) {
  const artifact = JSON.parse(
    await readFile(resolve(root, artifactPath), "utf8"),
  );
  exports.push(
    `export const ${name} = ${JSON.stringify(artifact.abi, null, 2)} as const;`,
  );
}

await writeFile(
  resolve(root, "src/lib/contracts/abi.ts"),
  `// Generated by pnpm export:abis. Do not edit manually.\n\n${exports.join(
    "\n\n",
  )}\n`,
);
